### ISSUE TITLE
Cannot find player

### ISSUE THREAD

**Issue by SenPr** [Syrent/VelocityReport#11]
I just installed the plugin, using /report on anyone just returns "Player not found"

**Comment by Syrent** [comment]
Hi,
Please answer the following questions:
1. Do You use the plugin on only Spigot or both Velocity and Spigot?
2. What Database method do you use?
3. Did you enable `velocity_support` in the `settings.yml` file?

**Comment by SenPr** [comment]
Everything is on default.

1. I tried both, neither worked
2. SQLite
3. No

**Comment by Syrent** [comment]
Try the new version:
https://github.com/Syrent/VelocityReport/releases/tag/v2.1.5

Let me know if it solves the problem

**Comment by SenPr** [comment]
Seems to have fixed it! There are some feature requests I have so I will also drop it here.

- Discord Integration (Either Webhook or DiscordSRV, webhook is probably preferable) - Sends a notification/webhook embed when a report is made
- Option to notify a player if their report has been Done/Processed

**Comment by Syrent** [comment]
Glad to hear it's fixed.
I'll try to add these features next week.
