### ISSUE TITLE
Don't work on 1.15.2 database

### ISSUE THREAD

**Issue by CrackBack11** [Syrent/VelocityReport#118]
### Server backend version

1.15.2

### Server Velocity version

3.1.1

### VelocityReport version

latest

### Describe the bug

the plugin work on 1.15.2 but the database don't work, dont create any table

### Expected behavior

1

### Steps to reproduce

1

### Additional info

1

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Fixed on 3.9.1
