### ISSUE TITLE
Action Bar not disappearing without reports.

### ISSUE THREAD

**Issue by siBalda** [Syrent/VelocityReport#128]
### Server backend version

1.20.1

### Server Velocity version

Velocity 3.2.0 build 37fedf50-b260

### VelocityReport version

3.9.1

### Describe the bug

Action bar display reports doesn't go away when reports are done.

### Expected behavior

The actionbar should be removed when there are no reports

### Steps to reproduce

1- Report a player
2- You will have an actionbar which tells you there is a report
3- Get the report
4- Open your reports and mark it as done
5- See the actionbar still be displayed

### Additional info

If I reload the plugin, even with /plugman reload, the action bar goes away.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Give this version a shot:
[VelocityReport v3.9.2.zip](https://github.com/Syrent/VelocityReport/files/12582518/VelocityReport.v3.9.2.zip)
I've made improvements to the MySQL code to enhance error handling. Please test this version and provide your complete server log for review.

**Comment by siBalda** [comment]
> Give this version a shot: [VelocityReport v3.9.2.zip](https://github.com/Syrent/VelocityReport/files/12582518/VelocityReport.v3.9.2.zip) I've made improvements to the MySQL code to enhance error handling. Please test this version and provide your complete server log for review.

No it is still bugged.

**Comment by siBalda** [comment]
[latest.log](https://github.com/Syrent/VelocityReport/files/12585737/latest.log)
[latest2.log](https://github.com/Syrent/VelocityReport/files/12585740/latest2.log)
[latest1.log](https://github.com/Syrent/VelocityReport/files/12585742/latest1.log)

**Comment by siBalda** [comment]
I think I will disable staff actionbar... it's the only solution at the moment.

**Comment by Syrent** [comment]
Should be fixed in 3.9.2
https://github.com/Syrent/VelocityReport/releases/tag/3.9.2
