### ISSUE TITLE
1.7.10

### ISSUE THREAD

**Issue by SladeHazard** [Syrent/VelocityReport#137]
### Server backend version

1.12.2

### Server Velocity version

3.0.2

### VelocityReport version

3.10.0

### Describe the bug

I run a pvp server and use ViaVersion but players who join with 1.7.10 client cannot use the report command as the book never opens, would it be possible to disable the book for them and only keep the command / make the report [player] redirect to the chat report command help message

### Expected behavior

book opens or the chat help message shows for typing /report [player]

### Steps to reproduce

report a player on 1.7.10

### Additional info

n/a

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Hey, you can directly use commands to report someone based on the mode that you choose in `settings.yml`:
- SIMPLE: `/report <player> <reason>`
- CATEGORY: `/report <player> <category> <reason>`

**Comment by SladeHazard** [comment]
> Hey, you can directly use commands to report someone based on the mode that you choose in `settings.yml`:
> 
> * SIMPLE: `/report <player> <reason>`
> * CATEGORY: `/report <player> <category> <reason>`

I'm aware of this, but when the 1.7.10 players executed only /report <player>, it simply does nothing, doesn't even send a message in chat
