### ISSUE TITLE
MySQL Optimization

### ISSUE THREAD

**Issue by SladeHazard** [Syrent/VelocityReport#155]
### Server backend version

Spigot 1.12.2

### Server Velocity version

N/A

### VelocityReport version

N/A

### Describe the bug

Hey, can you please optimize your MySQL usage so it doesn't take performance.. the plugin is idle with 0 players online on the server and shows up on both timings and spark as the top consumer..

![image](https://github.com/Syrent/VelocityReport/assets/45261094/d5f64717-6cb1-4def-b5d9-0ddb98108b4b)

### Expected behavior

0% usage

### Steps to reproduce

Install the plugin and use MySQL

### Additional info

N/A

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [X] I ticked all of the boxes without actually reading them

**Comment by SladeHazard** [comment]
![image](https://github.com/Syrent/VelocityReport/assets/45261094/a4a98e96-c9fc-4eb8-98ce-9198608ba733)
:joy:

**Comment by SladeHazard** [comment]
![image](https://github.com/Syrent/VelocityReport/assets/45261094/3d438c7d-b40d-4726-aca5-4913cc18b689)

also I have over 20+ plugins that are more complex than this using mysql which with this doesn't happen, hikari

**Comment by Syrent** [comment]
All database operations in this plugin are executed asynchronously, meaning that they are split across multiple threads and handled independently. This approach introduces additional checks for data integrity and consistency, which can slightly increase execution times compared to plugins that utilize synchronous database operations. However, the trade-off is a more responsive and efficient main server thread, ensuring smooth overall application performance.

While the current asynchronous execution setup provides a compelling balance between performance and data safety, you can further optimize it by adjusting the thread pool size in the database configuration file. This setting controls the number of worker threads dedicated to handling asynchronous database tasks, allowing you to fine-tune the performance according to your specific requirements.

**Comment by SladeHazard** [comment]
> All database operations in this plugin are executed asynchronously, meaning that they are split across multiple threads and handled independently. This approach introduces additional checks for data integrity and consistency, which can slightly increase execution times compared to plugins that utilize synchronous database operations. However, the trade-off is a more responsive and efficient main server thread, ensuring smooth overall application performance.
> 
> While the current asynchronous execution setup provides a compelling balance between performance and data safety, you can further optimize it by adjusting the thread pool size in the database configuration file. This setting controls the number of worker threads dedicated to handling asynchronous database tasks, allowing you to fine-tune the performance according to your specific requirements.

Yeah I understand that but it's weird how this is implemented because a report plugin isn't necessarily going to be extensive in the first place and this happens while it's idle, I have other popular plugins which utilize ASYNC MySQL and they do not such checks, such as AjLeaderboards https://www.spigotmc.org/resources/ajleaderboards.85548/. and It's generally recommended against using async operations unless the operations are extensive in the first place which in this case aren't for a reports plugin
