### ISSUE TITLE
velocityreport + libertybans

### ISSUE THREAD

**Issue by frogglen** [Syrent/VelocityReport#71]
### Server backend version

purpur 1.19.3

### Server Velocity version

velocity lastets

### VelocityReport version

3.7.1

### Describe the bug

We have detected bugs on your server which threaten your server's stability.
LibertyBans will continue to operate unaffected, but we strongly suggest you fix these bugs.
These bugs are (most likely) due to other plugins' mistakes. Each of the following plugins has shaded a library but did not relocate it. You should report each bug to the plugin author.
Plugin Name | Library Name | Class Detected
----------------------------------------------
Plugin 'VelocityReport 3.7.1' | HikariCP | com.zaxxer.hikari.HikariConfig
Note for advanced users: Understanding the consequences, you can minimize this warning by setting the system property libertybans.relocationbug.disablecheck to 'true'
*******************************************

### Expected behavior

These bugs are (most likely) due to other plugins' mistakes. Each of the following plugins has shaded a library but did not relocate it. 

### Steps to reproduce

instals velocityreport + libertybans

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
Hi, I'll fix it ASAP.
thanks for reporting this problem

**Comment by Syrent** [comment]
Fixed in 3.7.2
