### ISSUE TITLE
Can't translate message and settings files

### ISSUE THREAD

**Issue by magef1x** [Syrent/VelocityReport#91]
### Server backend version

Paper 1.19.4 Build 490

### Server Velocity version

Velocity 3.2.0 Build 247

### VelocityReport version

3.8.0

### Describe the bug

I want to configurate the settings and language file but itsn't updating to new translated files. Can u add file structure like enchanced velocity? It will be easier for other developers and maybe it will be a solution to my problem.
![image](https://user-images.githubusercontent.com/114337601/229869891-2556eefd-4fc5-44ab-a6aa-7de171fddd5f.png)

### Expected behavior

These are the translated files 

1) Settings.yml https://cdn.discordapp.com/attachments/985981259127877702/1092862726088425613/settings.yml
2) Language file (en_US.yml) https://cdn.discordapp.com/attachments/985981259127877702/1092862726533042237/en_US.yml

### Steps to reproduce

Step 1: Download the latest Velocity Report.
Step 2: Try to change settings.yml and en_US.yml of plugin.
Step 3: Save the changes.
Step 3: Restart your server.

### Checklist

- [X] I am running latest version of the plugin
- [X] I have read the wiki to make sure it's not an issue with configuration
- [ ] I ticked all of the boxes without actually reading them

**Comment by Syrent** [comment]
https://github.com/Syrent/VelocityVanish/issues/147#issuecomment-1500009436
